# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: prod

import:
  - catalog/hello-world

components:
  terraform:
    hello-world:
      vars:
        location: eastus
        vnet_address_space:  ["10.0.0.0/16"]
        instance_count: 10
        vm_sku: Standard_B12ms
