# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

vars:
  stage: staging

import:
  - catalog/hello-world

components:
  terraform:
    hello-world:
      vars:
        location: eastus
        vnet_address_space:  ["10.1.0.0/16"]
